services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hottakes_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: fastapi-backend
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://admin:password@mysql-db:3306/hottakes_db"
      OPENCAGE_API_KEY: "${OPENCAGE_API_KEY}"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: vite-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://localhost:8000"

volumes:
  mysql_data:
